# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Controllers for singular joint ------------------------------------  
# 
# Forward Position Controllers ---------------------------------------
PositionJointInterface_joint_group_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

# Controllers for singular joint ------------------------------------
# 
# Effort Position Controllers ---------------------------------------

# VALUES ARE NOT CORRECT !
EffortJointInterface_joint_group_controller:
  type:  effort_controllers/JointGroupPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  pid: {p: 800.0, i: 100, d: 80.0, i_clamp_min: -10000, i_clamp_max: 10000}

# Forward Velocity Controllers ---------------------------------------
VelocityJointInterface_joint_group_controller:
  type:  velocity_controllers/JointGroupPositionController
  joints:
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

## iiwa Trajectory Controllers
  #   
  # Effort Position Controllers ---------------------------------------
EffortJointInterface_trajectory_controller:
  type: effort_controllers/JointTrajectoryController
  joints: 
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    
    # VALUES ARE NOT CORRECT !
  gains:
    iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30}
    iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
    iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
    iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
    iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
    iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
    iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default
  
  # Forward Position Controllers ---------------------------------------
PositionJointInterface_trajectory_controller:
  type: position_controllers/JointTrajectoryController
  joints: 
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7

  constraints:
    goal_time: 0.5                     # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default
  
  # Forward Velocity Controllers ---------------------------------------
VelocityJointInterface_trajectory_controller:
  type: velocity_controllers/JointVelocityController
  joints: 
    - iiwa_joint_1
    - iiwa_joint_2
    - iiwa_joint_3
    - iiwa_joint_4
    - iiwa_joint_5
    - iiwa_joint_6
    - iiwa_joint_7
    
    # VALUES ARE NOT CORRECT !
  gains:
    iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30}
    iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
    iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
    iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
    iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
    iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
    iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}

  constraints:
    goal_time: 0.5                   # Override default

  state_publish_rate:  25            # Override default
  action_monitor_rate: 30            # Override default
  stop_trajectory_duration: 0        # Override default

## UR Trajectory Controllers
ur_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - shoulder_pan_joint
     - shoulder_lift_joint
     - elbow_joint
     - wrist_1_joint
     - wrist_2_joint
     - wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      shoulder_pan_joint: {trajectory: 0.1, goal: 0.1}
      shoulder_lift_joint: {trajectory: 0.1, goal: 0.1}
      elbow_joint: {trajectory: 0.1, goal: 0.1}
      wrist_1_joint: {trajectory: 0.1, goal: 0.1}
      wrist_2_joint: {trajectory: 0.1, goal: 0.1}
      wrist_3_joint: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  # gazebo_ros_control:
  #   pid_gains:
  #     shoulder_pan_joint:
  #       p:100.0
  #       i:0.01
  #       d:10.0
  #     shoulder_lift_joint:
  #       p:100.0
  #       i:0.01
  #       d:10.0
  #     elbow_joint:
  #       p:100.0
  #       i:0.01
  #       d:10.0
  #     wrist_1_joint:
  #       p:100.0
  #       i:0.01
  #       d:10.0
  #     wrist_2_joint:
  #       p:100.0
  #       i:0.01
  #       d:10.0
  #     wrist_3_joint:
  #       p:100.0
  #       i:0.01
  #       d:10.0
  